version: '3.8'

services:
  app:
    image: node-docker-swarm:1.0
    build:
      context: .
    deploy:
      replicas: 4
    environment:
      - PORT=3000
    networks:
      - app-network

  nginx:
    image: nginx
    ports:
      - "8000:80" # Expose NGINX on port 8000
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf # Mount the NGINX configuration
    deploy:
      replicas: 1
    networks:
      - app-network
    depends_on:
      - app

networks:
  app-network:
    driver: overlay
